=== juanifcd0210/curso/MF0491_3 Cliente 180H/UF1841 60H/E2/xml/futbol.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD generado con XMLSpy v2019 rel. 3 sp1 (x64) (http://www.altova.com) -->
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT equipo (nombre, ciudad, entrenador, jugadores)>
<!ELEMENT futbol (#PCDATA | equipo)*>
<!ATTLIST futbol
	xsi:noNamespaceSchemaLocation CDATA #IMPLIED
	xmlns:xsi CDATA #FIXED "http://www.w3.org/2001/XMLSchema-instance"
>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT jugador (nombre, nacionalidad)>
<!ATTLIST jugador
	posicion (defensa | delantero | portero) #IMPLIED
	posicicion CDATA #FIXED "delantero"
>
<!ELEMENT jugadores (jugador+)>
<!ELEMENT entrenador EMPTY>
<!ELEMENT nacionalidad (#PCDATA)>

=== juanifcd0210/curso/xml/futbol.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE futbol SYSTEM "C:\_IFCD0210\MF0491_3 Cliente 180H\UF1841 60H\E2\futbol.dtd">
<futbol xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/_IFCD0210/MF0491_3%20Cliente%20180H/UF1841%2060H/E2/futbol.xsd"> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/Alumnos/Desktop/prueba.xsd">
	<equipo>
		<nombre>Levante</nombre>
		<ciudad>Valencia</ciudad>
		<entrenador/>
		<jugadores>
			<jugador posicion="portero">
				<nombre>Javier Jiménez</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="delantero">
				<nombre>Nong</nombre>
				<nacionalidad>camerunés</nacionalidad>
			</jugador>
		</jugadores>
	</equipo>
	<equipo>
		<nombre>Real Sociedad</nombre>
		<ciudad>San Sebastián</ciudad>
		<entrenador/>
		<jugadores>
			<jugador posicion="portero">
				<nombre>Claudio Bravo</nombre>
				<nacionalidad>chilena</nacionalidad>
			</jugador>
			<jugador posicion="defensa">
				<nombre>Mikel González</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
		</jugadores>
	</equipo>
	<equipo>
		<nombre>Tenerife></nombre>
		<ciudad>Tenerife</ciudad>
		<entrenador/>
		<jugadores>
			<jugador posicicion="delantero">
				<nombre>Nano Mesa</nombre>
				<nacionalidad>española</nacionalidad>
			</jugador>
			<jugador posicion="portero">
				<nombre>Dani Hernández</nombre>
				<nacionalidad>venezolana</nacionalidad>
			</jugador>
		</jugadores>
	</equipo>
</futbol>
